require_relative '../../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.4'
prepare_react_native_project!

target 'NativeRuntimeTests' do
  use_react_native!(
    :path => '../../node_modules/react-native',
    :app_path => File.expand_path('../..', __dir__)
  )

  post_install do |installer|
    react_native_post_install(installer, '../../node_modules/react-native')
  end
end
