import { StyleSheet } from "react-native";

export const ROW_WIDTH = 320;

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  homeContent: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 32,
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#d8d8d8",
  },
  headerWithBack: {
    gap: 12,
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: "#171717",
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    color: "#5f6368",
  },
  exampleList: {
    gap: 12,
    marginTop: 18,
  },
  exampleCard: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#c7ccd1",
    borderRadius: 8,
    backgroundColor: "#f8fafc",
  },
  exampleCardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#171717",
  },
  exampleCardDescription: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: "#4b5563",
  },
  backButton: {
    alignSelf: "flex-start",
    justifyContent: "center",
    minHeight: 34,
    paddingHorizontal: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#b7bec7",
    borderRadius: 6,
    backgroundColor: "#ffffff",
  },
  backButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1f2937",
  },
  toolbar: {
    maxHeight: 54,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#d8d8d8",
  },
  toolbarContent: {
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  button: {
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: "#1f6feb",
  },
  buttonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ffffff",
  },
  summary: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#d8d8d8",
  },
  summaryText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#4b5563",
  },
  row: {
    justifyContent: "center",
    width: ROW_WIDTH,
    paddingHorizontal: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#8a8a8a",
  },
  rowTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#171717",
  },
  rowText: {
    marginTop: 4,
    fontSize: 14,
    color: "#333333",
  },
  rowMeta: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: "700",
    color: "#555555",
  },
  dynamicRow: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#b9c0c9",
    borderRadius: 8,
  },
  dynamicHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dynamicAccent: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  dynamicTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
    color: "#171717",
  },
  dynamicBody: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: "#343a40",
  },
  dynamicMeta: {
    marginTop: 10,
    fontSize: 12,
    fontWeight: "700",
    color: "#59636e",
  },
  chatRow: {
    alignSelf: "stretch",
    paddingHorizontal: 24,
    paddingVertical: 5,
  },
  chatListContent: {
    paddingTop: 12,
    paddingBottom: 20,
  },
  chatRowOwn: {
    alignItems: "flex-end",
  },
  chatRowOther: {
    alignItems: "flex-start",
  },
  chatBubble: {
    maxWidth: "78%",
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
  },
  chatBubbleOwn: {
    backgroundColor: "#dff5e7",
    borderColor: "#acd3ba",
  },
  chatBubbleOther: {
    backgroundColor: "#eef2ff",
    borderColor: "#c5ccef",
  },
  chatAuthor: {
    marginBottom: 3,
    fontSize: 12,
    fontWeight: "700",
    color: "#445066",
  },
  chatAuthorHidden: {
    height: 0,
    marginBottom: 0,
    opacity: 0,
  },
  chatMessage: {
    fontSize: 15,
    lineHeight: 20,
    color: "#15171a",
  },
  chatMeta: {
    marginTop: 5,
    fontSize: 11,
    fontWeight: "700",
    color: "#68717f",
  },
  chatReactions: {
    maxWidth: "78%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    marginTop: 3,
  },
  chatReactionsHidden: {
    height: 0,
    marginTop: 0,
    opacity: 0,
  },
  chatReactionChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#cfd4dc",
    backgroundColor: "#ffffff",
  },
  chatReactionChipHidden: {
    width: 0,
    height: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: 0,
    opacity: 0,
  },
  chatReactionText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#343a40",
  },
  feedListContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
  },
  feedCard: {
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d7dde5",
    borderRadius: 8,
    backgroundColor: "#ffffff",
  },
  feedHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
  },
  feedAvatar: {
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  feedAvatarText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#1d4ed8",
  },
  feedPersonCopy: {
    flex: 1,
    gap: 2,
  },
  feedPersonName: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  feedPersonMeta: {
    fontSize: 13,
    color: "#64748b",
  },
  feedKindBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "#eef2ff",
  },
  feedKindBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#4338ca",
    textTransform: "capitalize",
  },
  feedCategoryChip: {
    alignSelf: "flex-start",
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
  },
  feedCategoryChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#334155",
  },
  feedSectionTitle: {
    marginBottom: 8,
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  feedBody: {
    fontSize: 14,
    lineHeight: 20,
    color: "#111827",
  },
  feedMediaCard: {
    justifyContent: "flex-end",
    marginBottom: 12,
    padding: 14,
    borderRadius: 8,
  },
  feedMediaLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#0f172a",
    opacity: 0.72,
    textTransform: "uppercase",
  },
  feedMediaTitle: {
    marginTop: 6,
    fontSize: 20,
    fontWeight: "800",
    color: "#0f172a",
  },
  feedMediaSubtitle: {
    maxWidth: 260,
    marginTop: 6,
    color: "#0f172a",
    opacity: 0.78,
  },
  feedPollList: {
    gap: 10,
    marginTop: 14,
  },
  feedPollOption: {
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d7dde5",
    borderRadius: 8,
    backgroundColor: "#f8fafc",
  },
  feedPollOptionSelected: {
    borderColor: "#60a5fa",
    backgroundColor: "#dbeafe",
  },
  feedPollOptionLabel: {
    fontWeight: "700",
    color: "#0f172a",
  },
  feedPollOptionVotes: {
    marginTop: 4,
    fontSize: 12,
    color: "#64748b",
  },
  feedQuoteCard: {
    marginBottom: 12,
    padding: 16,
    borderLeftWidth: 4,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
  },
  feedQuoteText: {
    marginBottom: 10,
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 30,
    color: "#0f172a",
  },
  feedEventBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  feedEventBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "#dcfce7",
  },
  feedEventBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#166534",
  },
  feedExpandedBody: {
    marginTop: 14,
    fontSize: 14,
    lineHeight: 22,
    color: "#334155",
  },
  feedActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
  },
  feedButton: {
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    backgroundColor: "#ffffff",
  },
  feedButtonActive: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  feedButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  feedButtonTextActive: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ffffff",
  },
  cardsListBackground: {
    flex: 1,
    backgroundColor: "#455f72",
  },
  cardsHeaderBlock: {
    alignSelf: "center",
    width: 100,
    height: 100,
    borderRadius: 8,
    backgroundColor: "#456aaa",
  },
  cardsLegendListHeader: {
    alignSelf: "center",
    width: 100,
    height: 100,
    marginHorizontal: 8,
    marginVertical: 8,
    borderRadius: 8,
    backgroundColor: "#456aaa",
  },
  cardsItemOuter: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  cardsItemContainer: {
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d9dee4",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.45,
    shadowRadius: 12,
    elevation: 4,
  },
  cardsHeaderContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  cardsAvatar: {
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    marginRight: 12,
    borderRadius: 20,
    backgroundColor: "#e5e7eb",
  },
  cardsAvatarText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#111827",
  },
  cardsHeaderText: {
    flex: 1,
  },
  cardsAuthorName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111111",
  },
  cardsTimestamp: {
    marginTop: 2,
    fontSize: 12,
    color: "#8a8f96",
  },
  cardsItemTitle: {
    marginBottom: 8,
    fontSize: 18,
    fontWeight: "700",
    color: "#111111",
  },
  cardsItemBody: {
    fontSize: 14,
    lineHeight: 20,
    color: "#5f6368",
  },
  cardsItemFooter: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    justifyContent: "flex-start",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#edf0f2",
  },
  cardsFooterText: {
    fontSize: 14,
    color: "#8a8f96",
  },
});
